# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3b2cfbb9fa8b02986bb8c73f424131d5312e9e9f66200e93802210b6a3cad0cfee8ca5b01b682c15a9be588cb8f20eb412f77c01d48f3b05853988cbc30d2d0

test:
  secret_key_base: cc534766e38a37f00746a1deff05916da7a121d47bd1e6dc134462efe39449382b09804b752711f29df8bb7a93c32cb21602b434079559ae8022108d35fe086b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
